fix: alias in pyhton 3.7 for python3 (#31)

diff --git a/Dockerfile.minimal b/Dockerfile.minimal
--- a/Dockerfile.minimal
+++ b/Dockerfile.minimal
@@ -1,5 +1,5 @@
 # Modified by .github/workflows/publish_docker.yml
-ARG CUDA_IMAGE=nvidia/cuda:9.2-base-ubuntu18.04
+ARG CUDA_IMAGE=nvidia/cuda:11.6.0-base-ubuntu20.04
 FROM $CUDA_IMAGE
 
 # Modified by .github/workflows/publish_docker.yml
@@ -24,26 +24,30 @@ RUN apt-get update && apt-get install -y \
  && export TZ=Europe/Moscow \
 # install minimal apps (python${PYTHON_VERSION}-distutils needed for python3.9)
  && apt-get install -y python${PYTHON_VERSION}-minimal python${PYTHON_VERSION}-distutils python3-pip \
- # link default python, python3, pip, pip3 to python${PYTHON_VERSION}
- && rm -f /usr/bin/python \
- && ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python \
- && rm -f /usr/bin/python3 \
- && ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 \
- && python --version \
- && python3 --version \
 # needed for substratools with python3.9
- && python -m pip install --upgrade --no-cache-dir pip setuptools\
- && pip --version \
- && pip3 --version \
+ && python${PYTHON_VERSION} -m pip install --upgrade --no-cache-dir pip setuptools \
 # install substratools
- && cd /tmp && python -m pip install --no-cache-dir . \
+ && cd /tmp && python${PYTHON_VERSION} -m pip install --no-cache-dir . \
 # remove all python packages but substratools
- && python -m pip uninstall -y setuptools pip \
+ && python${PYTHON_VERSION} -m pip uninstall -y setuptools pip \
 # remove all apps but python
  && apt-get remove -y python3-pip python${PYTHON_VERSION}-distutils software-properties-common --purge --autoremove \
 # clean the apt cache
  && apt-get clean \
- && rm -rf /var/lib/apt/lists/*
+ && rm -rf /var/lib/apt/lists/* \
+# Link python and python 3 to python${PYTHON_VERSION}
+ && if ! command -v python &> /dev/null; \
+    then echo "python not found, creating alias" \
+    && rm -f /usr/bin/python \
+    && ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python; \
+ fi \
+ && if ! command -v python3 &> /dev/null; \
+    then echo "python3 not found, creating alias" \
+    && rm -f /usr/bin/python3 \
+    && ln -s /usr/bin/python${PYTHON_VERSION} /usr/bin/python3; \
+ fi \
+ && if python --version | grep -q "Python ${PYTHON_VERSION}"; then echo "python command is properly set"; else exit 1 ; fi \
+ && if python3 --version | grep -q "Python ${PYTHON_VERSION}"; then echo "python3 command is properly set"; else exit 1 ; fi
 
 # Create default user, group, and home directory
 RUN addgroup --gid ${GROUP_ID} ${GROUP_NAME}
